import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Parallel Route",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  left,
}: Readonly<{
  children: React.ReactNode;
  left: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-[5fr_1fr] h-screen">
      {children}
      {left}
    </div>
  );
}
