import { CommonLayout } from "@/components/common/SideBar";
import { userSideBarConfig } from "@/lib/sidebar-config";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Users",
  description: "Generated by create next app",
};

const links = [
  { href: "/", label: "Home" },
  { href: "/profile", label: "Profile" },
  { href: "/settings", label: "Settings" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CommonLayout
      sidebarConfig={userSideBarConfig}
      headerTitle="Users"
      showSidebar
    >
      {children}
    </CommonLayout>
  );
}
